spring:
  application:
    name: order-service
  datasource:
    url: ${SPRİNG_DATASOURCE_URL}
    username: ${SPRİNG_DATASOURCE_USERNAME}
    password: ${SPRİNG_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
      - localhost:49092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
        enable.idempotence: true
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.semih.*"
        spring.json.use.type.headers: true
    properties:
      topics:
        order-events: order-events-topic
        basket-events: basket-events-topic
        inventory-response: inventory-response-topic
        order-basket-result: order-basket-result-topic


server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans