spring:
  application:
    name: product-service
  datasource:
    url: ${SPRİNG_DATASOURCE_URL}
    username: ${SPRİNG_DATASOURCE_USERNAME}
    password: ${SPRİNG_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          json_format_mapper: jackson

  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
      - localhost:49092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
        enable.idempotence: true
    consumer:
      group-id: product-response-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.semih.*"
        spring.json.use.type.headers: true
    properties:
      topics:
        product-events: product-events-topic
        product-stock-response-events: product-stock-response-events

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED   # Son N çağrı üzerinden hata oranını hesapla (zaman yerine çağrı sayısı)
        slidingWindowSize: 50            # Son 50 isteği analiz et (denge için yaygın değer)
        minimumNumberOfCalls: 20         # En az 20 çağrı olmadan failure rate hesaplama (yanlış alarmı önler)
        failureRateThreshold: 50         # Hata oranı %50’yi geçerse circuit OPEN olur
        waitDurationInOpenState: 30s     # Devre açıldıktan sonra 30 sn bekle, sonra HALF_OPEN’a geç
        permittedNumberOfCallsInHalfOpenState: 10  # Servis iyileşti mi test etmek için izin verilen deneme isteği sayısı
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Süre dolunca otomatik HALF_OPEN’a geç



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 0